### PR TITLE
fa: Update Persian translation

### PR DESCRIPTION
**Pull request by reza-agahi**
Review and update the problems discussed in #110.

### CODE REVIEW

**Comment by reza-agahi** [comment]
Hi Hadi!
I just updated the motivation section to get started.
If you agree with the mentioned issues in #110, I can keep going with resolving them. Otherwise, let me know your ideas and plans for reviewing and improving the translation.
Thanks

**Comment by hadisinaee** [comment]
Hi Reza,
Thanks. I totally agree with that 👍

**Review by hadisinaee — APPROVED** [review]

**Review by hadisinaee — APPROVED** [review]

**Comment by vghaderi** [comment]
Hi. How can I help with this translation? Did you publish it anywhere?

**Comment by hadisinaee** [comment]
Hi,

These are the things that I think you can have a contribution:
- you can update the doc with its latest version, e.x. translating new parts
- you can help with bad translations
- you can help with doc styling for Persian/Farsi readers

Feel free to add what you may think is missed. Please, send a pull request for each contribution so that others can review it quickly.

**Comment by Azooze0533** [comment]
😗 bejwjq. 😃

**Pull request merged**
